### ISSUE TITLE
Chef_Install

### ISSUE THREAD

**Issue by dantesolo** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#304]
I know the VM setup should be easy but I am experiencing an issue that I can't get past. I am on a Windows 10 machine. Any help would be greatly appreciated. 

Vagrant attempted to execute the capability 'chef_install'
on the detect guest OS 'linux', but the guest doesn't
support that capability. This capability is required for your
configuration of Vagrant. Please either reconfigure Vagrant to
avoid this capability or fix the issue by creating the capability.

**Comment by rreben** [comment]
Which version of vmbox are you using?

**Comment by ultrasounder** [comment]
Hi 
I am on a MAC OSX ElCapitan and I am having the same issues. Vagrant version 1.8.5 and Virtualbox version 5.0.26(.July 18th release).

**Comment by rreben** [comment]
I made a fork, with some adjustments. It is working for me (Windows 7). https://github.com/rreben/Mining-the-Social-Web-2nd-Edition

**Comment by ultrasounder** [comment]
@rreben thanks much. I tried your git repo on my said MAC configuration and I can confirm
it works. Thanks for your fork and contribution.

**Comment by rreben** [comment]
you are welcome, it is good to hear that it is working on the Mac as well.

**Comment by tanju-b** [comment]
@rreben another thank you. after struggling for quite some time with original repo, confirming that this fork worked for me.  Running Windows 10

**Comment by rreben** [comment]
U are wellcome!

**Comment by AlgoTrdr** [comment]
@rreben Thanks for your fork.  Although it gets much further than the original, I still can't get it to work.  It seems to fail when trying to install boilerpipe.  Here's the output from my command widow:

==> default:     - install package python_pip[charade] version 1.0.3
==> default:   * python_pip[boilerpipe] action install
==> default: [2016-12-27T04:21:46+00:00] INFO: Installing python_pip[boilerpipe] version 1.2.0.0
==> default:
==> default:
==> default: ================================================================================
==> default:
==> default: Error executing action `install` on resource 'python_pip[boilerpipe]'
==> default:
==> default: ================================================================================
==> default:
==> default:
==> default:     Mixlib::ShellOut::ShellCommandFailed
==> default:     ------------------------------------
==> default:     Expected process to exit with [0], but received '1'
==> default:     ---- Begin output of pip install  boilerpipe==1.2.0.0 ----
==> default:     STDOUT: Collecting boilerpipe==1.2.0.0
==> default:       Downloading boilerpipe-1.2.0.0.tar.gz (1.3MB)
==> default:         Complete output from command python setup.py egg_info:
==> default:         Traceback (most recent call last):
==> default:           File "<string>", line 1, in <module>
==> default:           File "/tmp/pip-build-LQ6USy/boilerpipe/setup.py", line 27, in <module>
==> default:             download_jars(datapath=DATAPATH)
==> default:           File "/tmp/pip-build-LQ6USy/boilerpipe/setup.py", line 21, in download_jars
==> default:             tar = tarfile.open(tgz_name, mode='r:gz')
==> default:           File "/usr/lib/python2.7/tarfile.py", line 1678, in open
==> default:             return func(name, filemode, fileobj, **kwargs)
==> default:           File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
==> default:             raise ReadError("not a gzip file")
==> default:         tarfile.ReadError: not a gzip file
==> default:
==> default:         ----------------------------------------
==> default:     STDERR: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
==> default:       SNIMissingWarning
==> default:     /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
==> default:       InsecurePlatformWarning
==> default:     Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LQ6USy/boilerpipe/
==> default:     ---- End output of pip install  boilerpipe==1.2.0.0 ----
==> default:     Ran pip install  boilerpipe==1.2.0.0 returned 1
==> default:
==> default:     Cookbook Trace:
==> default:     ---------------
==> default:     /var/chef/cache/cookbooks/python/providers/pip.rb:155:in `pip_cmd'
==> default:     /var/chef/cache/cookbooks/python/providers/pip.rb:139:in `install_package'
==> default:     /var/chef/cache/cookbooks/python/providers/pip.rb:46:in `block (2 levels) in class_from_file'
==> default:     /var/chef/cache/cookbooks/python/providers/pip.rb:44:in `block in class_from_file'
==> default:
==> default:     Resource Declaration:
==> default:     ---------------------
==> default:     # In /var/chef/cache/cookbooks/mtsw2e/recipes/default.rb
==> default:
==> default:     163: python_pip "boilerpipe" do
==> default:     164:   version "1.2.0.0"
==> default:     165: end
==> default:     166: python_pip "ipython" do
==> default:
==> default:     Compiled Resource:
==> default:     ------------------
==> default:     # Declared in /var/chef/cache/cookbooks/mtsw2e/recipes/default.rb:163:in `from_file'
==> default:
==> default:     python_pip("boilerpipe") do
==> default:       action :install
==> default:       retries 0
==> default:       retry_delay 2
==> default:       default_guard_interpreter :default
==> default:       declared_type :python_pip
==> default:       cookbook_name "mtsw2e"
==> default:       recipe_name "default"
==> default:       version "1.2.0.0"
==> default:       package_name "boilerpipe"
==> default:     end
==> default:
==> default:     Platform:
==> default:     ---------
==> default:     x86_64-linux
==> default:
==> default: [2016-12-27T04:21:47+00:00] INFO: Running queued delayed notifications before re-raising exception
==> default: Running handlers:
==> default: [2016-12-27T04:21:47+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-12-27T04:21:47+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 60 resources updated in 07 minutes 18 seconds
==> default: [2016-12-27T04:21:47+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-12-27T04:21:47+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-12-27T04:21:47+00:00] ERROR: python_pip[boilerpipe] (mtsw2e::default line 163) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
==> default: ---- Begin output of pip install  boilerpipe==1.2.0.0 ----
==> default: STDOUT: Collecting boilerpipe==1.2.0.0
==> default:   Downloading boilerpipe-1.2.0.0.tar.gz (1.3MB)
==> default:     Complete output from command python setup.py egg_info:
==> default:     Traceback (most recent call last):
==> default:       File "<string>", line 1, in <module>
==> default:       File "/tmp/pip-build-LQ6USy/boilerpipe/setup.py", line 27, in <module>
==> default:         download_jars(datapath=DATAPATH)
==> default:       File "/tmp/pip-build-LQ6USy/boilerpipe/setup.py", line 21, in download_jars
==> default:         tar = tarfile.open(tgz_name, mode='r:gz')
==> default:       File "/usr/lib/python2.7/tarfile.py", line 1678, in open
==> default:         return func(name, filemode, fileobj, **kwargs)
==> default:       File "/usr/lib/python2.7/tarfile.py", line 1730, in gzopen
==> default:         raise ReadError("not a gzip file")
==> default:     tarfile.ReadError: not a gzip file
==> default:
==> default:     ----------------------------------------
==> default: STDERR: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (Subject Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#snimissingwarning.
==> default:   SNIMissingWarning
==> default: /usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/security.html#insecureplatformwarning.
==> default:   InsecurePlatformWarning
==> default: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-LQ6USy/boilerpipe/
==> default: ---- End output of pip install  boilerpipe==1.2.0.0 ----
==> default: Ran pip install  boilerpipe==1.2.0.0 returned 1
==> default: [2016-12-27T04:21:47+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

I'm using Windows 10, Vagrant 1.9.1, VirtualBox 5.1.12.

**Comment by rreben** [comment]
Yup. pip is broken (finally, due to outdated versions / recipes). Right now there is only a work around via basket4py (have a look at #317 )
