### ISSUE TITLE
hef never successfully completed!  error

### ISSUE THREAD

**Issue by jclaranjo** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#318]
Getting the command "Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete " Don't know how to proceed.

Kind Refards,

José Marques

==> default: Platform:
==> default: ---------
==> default: x86_64-linux
==> default: 
==> default: 
==> default: [2016-12-08T17:54:22+00:00] DEBUG: Re-raising exception: SyntaxError - /var/chef/cache/cookbooks/python/attributes/default.rb:42: syntax error, unexpected tIDENTIFIER, expecting end-of-input
==> default: ...n']['pip_script_url'] = ''https://bootstrap.pypa.io/get-pip....
==> default: ...                               ^
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/mixin/from_file.rb:30:in `from_file'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/dsl/include_attribute.rb:31:in `each'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:182:in `load_attribute_file'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:171:in `load_attributes_from_cookbook'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context.rb:187:in `load'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:510:in `setup_run_context'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:280:in `run'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/solo.rb:226:in `run'
==> default:   /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-solo:25:in `<top (required)>'
==> default:   /usr/bin/chef-solo:54:in `load'
==> default:   /usr/bin/chef-solo:54:in `<main>'
==> default: 
==> default: Running handlers:
==> default: [2016-12-08T17:54:22+00:00] ERROR: Running exception handlers
==> default: Running handlers complete
==> default: [2016-12-08T17:54:22+00:00] ERROR: Exception handlers complete
==> default: Chef Client failed. 0 resources updated in 02 seconds
==> default: [2016-12-08T17:54:22+00:00] DEBUG: Server doesn't support resource history, skipping resource report.
==> default: [2016-12-08T17:54:22+00:00] DEBUG: Audit Reports are disabled. Skipping sending reports.
==> default: [2016-12-08T17:54:22+00:00] FATAL: Stacktrace dumped to /var/chef/cache/chef-stacktrace.out
==> default: [2016-12-08T17:54:22+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
==> default: [2016-12-08T17:54:22+00:00] DEBUG: SyntaxError: /var/chef/cache/cookbooks/python/attributes/default.rb:42: syntax error, unexpected tIDENTIFIER, expecting end-of-input
==> default: ...n']['pip_script_url'] = ''https://bootstrap.pypa.io/get-pip....
==> default: ...                               ^
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/mixin/from_file.rb:30:in `instance_eval'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/mixin/from_file.rb:30:in `from_file'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/dsl/include_attribute.rb:39:in `block in include_attribute'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/dsl/include_attribute.rb:31:in `each'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/dsl/include_attribute.rb:31:in `include_attribute'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:182:in `load_attribute_file'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:171:in `load_attributes_from_cookbook'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:110:in `block in compile_attributes'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:109:in `each'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:109:in `compile_attributes'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context/cookbook_compiler.rb:72:in `compile'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/run_context.rb:187:in `load'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/policy_builder/expand_node_object.rb:97:in `setup_run_context'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:510:in `setup_run_context'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/client.rb:280:in `run'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:294:in `block in fork_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:282:in `fork_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:247:in `block in run_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/local_mode.rb:44:in `with_server_connectivity'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:235:in `run_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:464:in `sleep_then_run_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:451:in `block in interval_run_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `loop'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:450:in `interval_run_chef_client'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/client.rb:434:in `run_application'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application.rb:59:in `run'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/lib/chef/application/solo.rb:226:in `run'
==> default: /opt/chef/embedded/lib/ruby/gems/2.3.0/gems/chef-12.16.42/bin/chef-solo:25:in `<top (required)>'
==> default: /usr/bin/chef-solo:54:in `load'
==> default: /usr/bin/chef-solo:54:in `<main>'
==> default: [2016-12-08T17:54:22+00:00] ERROR: /var/chef/cache/cookbooks/python/attributes/default.rb:42: syntax error, unexpected tIDENTIFIER, expecting end-of-input
==> default: ...n']['pip_script_url'] = ''https://bootstrap.pypa.io/get-pip....
==> default: ...                               ^
==> default: [2016-12-08T17:54:22+00:00] FATAL: Chef::Exceptions::ChildConvergeError: Chef run process exited unsuccessfully (exit code 1)
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

**Comment by rreben** [comment]
Pls see #317
