### ISSUE TITLE
Chef never successfully completed

### ISSUE THREAD

**Issue by d2max** [ptwobrussell/Mining-the-Social-Web-2nd-Edition#326]
Hi,

I got an error message when I ran 'vagrant up' after installing VirtualBox and Vagrant. I'm using macbook pro i7 core with OS X Yosemite.

The error message shown at the end of the codes is:

Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

So I went up and found another error message:
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/python/attributes/default.rb

I tried 'vagrant destroy' and 'vagrant up' again, and got the same error message. Can you please help?

Thanks,
Di

**Comment by paulhyo** [comment]
I have the same problem:
MacBook Air, OSX El Captain 10.11.6
VirtualBox: 5.1.22 r115126 (Qt5.6.2)
Vagrant: 1.9.7

Error:
Chef never successfully completed! Any errors should be visible in the
output above. Please fix your recipes so that they properly complete.

Ouptut:
==> default: [2017-07-11T19:57:17+00:00] DEBUG: Filtered backtrace of compile error: /var/chef/cache/cookbooks/python/attributes/default.rb:23:in `from_file'
==> default: [2017-07-11T19:57:17+00:00] DEBUG: Backtrace entry for compile error: '/var/chef/cache/cookbooks/python/attributes/default.rb:23:in `from_file''
==> default: [2017-07-11T19:57:17+00:00] DEBUG: Line number of compile error: '23'
==> default: 
==> default: ================================================================================
==> default: Recipe Compile Error in /var/chef/cache/cookbooks/python/attributes/default.rb
==> default: ================================================================================
==> default: 
==> default: 
==> default: NoMethodError
==> default: -------------
==> default: undefined method `python' for #<Chef::Node::Attribute:0x00000002e5c2c8>
==> default: 
==> default: Cookbook Trace:
==> default: ---------------
==> default:   /var/chef/cache/cookbooks/python/attributes/default.rb:23:in `from_file'
==> default: 
==> default: Relevant File Content:
==> default: ----------------------
==> default: /var/chef/cache/cookbooks/python/attributes/default.rb:
==> default: 
==> default:  16:  # WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
==> default:  17:  # See the License for the specific language governing permissions and
==> default:  18:  # limitations under the License.
==> default:  19:  #
==> default:  20:  
==> default:  21:  default['python']['install_method'] = 'package'
==> default:  22:  
==> default:  23>> if python['install_method'] == 'package'
==> default:  24:    case platform
==> default:  25:    when "smartos"
==> default:  26:      default['python']['prefix_dir']         = '/opt/local'
==> default:  27:    else
==> default:  28:      default['python']['prefix_dir']         = '/usr'
==> default:  29:    end
==> default:  30:  else
==> default:  31:    default['python']['prefix_dir']         = '/usr/local'
==> default:  32:  end
==> default: 
==> default: System Info:
==> default: ------------
==> default: chef_version=13.2.20
==> default: platform=ubuntu
==> default: platform_version=12.04
==> default: ruby=ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
==> default: program_name=chef-solo worker: ppid=2090;start=19:57:12;
==> default: executable=/opt/chef/bin/chef-solo
==> default:

**Comment by DChildsy** [comment]
The (python) is deprecated and does not work with Chef 13. Should be using poise-python instead.

**Comment by sowm2006** [comment]
I have been trying to install the virtual environment on my macbook ios 10.12.6 and when I run the vagrant up command, I get message that chef never completed successfully. The failure is in the install of the python package or in finding the python method. How do I fix this?
